version: '3'
services:
  php-simple-web:
    build: .
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=agileadvn
      - MYSQL_DATABASE=agileadvn
      - MYSQL_USER=agileadvn
      - MYSQL_PASSWORD=agileadvn
