version: '3'
services:
  jenkins:
    image: wayarmy/jenkins-php:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
      - "9092:9092"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres/sonar
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_DB=sonar